### ISSUE TITLE
Demo shows only mailboxes, no messages

### ISSUE THREAD

**Issue by sk33wiff** [jmapio/jmap-demo-webmail#1]
Hi, I'm trying to use the demo with a gmail account proxied through proxy.jmap.io but only the mailboxes are displayed, no messages. Any ideas?

https://proxy.jmap.io/client/?debug=1&k=8103f136-46ee-11e5-8323-0026b9fac7aa

![screenshot from 2015-08-21 18 49 53](https://cloud.githubusercontent.com/assets/1010930/9404775/8dbe566c-4835-11e5-9897-057edba18a00.png)

**Comment by neilj** [comment]
Sorry for the delayed response. The issue here will be with the data not coming through the proxy (possibly a security restriction in the Gmail account or something). Please file an issue with the jmap-perl repo (the proxy codebase) and the right people will have a look for you: https://github.com/jmapio/jmap-perl

Thanks.

**Comment by sk33wiff** [comment]
No worries, thank you
